bookme_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('users/', include('users.urls')),
]

library/urls.py
from . import views
from django.urls import path


urlpatterns = [
    # Route for the books search page
    path("", views.books_search, name="books_search"),
    # Route for the books search results page
    path("books/", views.books_search_results, name="books_search_results"),
    # Route for the book detail page
    path("book/detail/<str:book_id>/", views.book_detail, name="book_detail"),
    # Route for adding a book to the user's favorites
    path("book/add_favorite/<str:book_id>/", views.add_book_to_favorites, name="add_book_to_favorites"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # Route for the user registration page
    path("register/", views.register_user, name="register_user"),
    # Route for the user login page
    path("login/", views.login_user, name="login_user"),
    # Route for the user logout page
    path("logout/", views.logout_user, name="logout_user"),
    # Route for the user profile page
    path("profile/", views.user_profile, name="user_profile"),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User

class FavoriteBook(models.Model):
    """
    This model represents a user's favorite book.
    It has a foreign key to the User model and a CharField to store the book's ID.
    The unique_together attribute ensures that each user can only have one favorite book with a given book ID.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book_id = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'book_id')

users/models.py
from django.db import models

# Create your models here.

library/views.py
import math
from django.shortcuts import render, redirect
from .utils import fecth_books, get_book_details
from urllib.parse import quote_plus
from django.contrib.auth.decorators import login_required
from .models import FavoriteBook
from django.http import HttpResponseRedirect

def books_search(request):
    """
    This function handles the books search page.
    It renders the books_search.html template and passes the request object to it.
    The view is the main entry point for the books search functionality.
    It showcases the search bar abd some static genres to search by.
    """
    return render(request, 'books_search.html')

def books_search_results(request):
    """
    This function handles the books search results page.
    It renders the results_list.html template and passes the request object to it.
    The view is the main entry point for the books search results functionality.
    It fetches the search query, limit, and page from the request object and uses them to fetch the books.
    It also calculates the total number of pages and passes them to the template.
    """
    search_query = request.GET.get('search')
    genre_query = request.GET.get('genre')
    limit = int(request.GET.get('limit', 10))
    page = int(request.GET.get('page', 1))
    offset = (page - 1) * limit

    if search_query:
        query = quote_plus(search_query)
    elif genre_query:
        query = f"subject:{quote_plus(genre_query)}"
    else:
        query = quote_plus("Jesus Christ")

    books, total_results = fecth_books(query, limit, offset)
    total_pages = math.ceil(total_results / limit) if total_results else 0

    context = {
        'title': search_query or genre_query,
        'query': search_query or genre_query,
        'books': books,
        'total_results': total_results,
        'total_pages': total_pages,
        'page': page,
        'limit': limit,
    }

    return render(request, 'results_list.html', context)

def book_detail(request, book_id):
    """
    This function handles the book detail page.
    It renders the book_detail.html template and passes the request object to it.
    The view is the main entry point for the book detail functionality.
    It fetches the book details from the Google Books API and passes them to the template.
    It also checks if the user is authenticated and if the book is in the user's favorites.
    If so, it shows a message saying that the book is already in the user's favorites.
    If not, it shows a button to add the book to the user's favorites.
    If the user is not authenticated, it shows a message saying that the user needs to login to add a book to their favorites.
    """
    is_favorite = False
    if request.user.is_authenticated:
        is_favorite = FavoriteBook.objects.filter(user=request.user, book_id=book_id).exists()
    book = get_book_details(book_id)
    return render(request, 'book_detail.html', {'book': book, 'is_favorite': is_favorite})

@login_required(login_url='/users/login/')
def add_book_to_favorites(request, book_id):
    """
    This function handles the add book to favorites functionality.
    It checks if the user is authenticated and if the book is not already in the user's favorites.
    If so, it creates a new FavoriteBook object and redirects the user to the book detail page.
    If not, it redirects the user to the book detail page.
    """
    if request.method == 'POST':
        if not FavoriteBook.objects.filter(user=request.user, book_id=book_id).exists():
            FavoriteBook.objects.create(user=request.user, book_id=book_id)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    else:
        return redirect('/')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from library.models import FavoriteBook
from library.utils import get_book_details

def register_user(request):
    """
    This function handles the user registration process.
    It checks if the request method is POST and if it is, it creates a new user using the UserCreationForm.
    If the request method is not POST, it creates a new UserCreationForm instance and renders the register.html template.
    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("users:user_profile")
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})

def login_user(request):
    """
    This function handles the user login process.
    It checks if the request method is POST and if it is, it logs the user in using the AuthenticationForm.
    If the request method is not POST, it creates a new AuthenticationForm instance and renders the login.html template.
    """
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("users:user_profile")

    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})

def logout_user(request):
    """
    This function handles the user logout process.
    It logs the user out and redirects them to the login page.
    """
    if request.method == "POST":
        logout(request)
        return redirect("/")

@login_required(login_url="/users/login/")
def user_profile(request):
    """
    This function handles the user profile page.
    It checks if the user is authenticated and if they are, it renders the user_profile.html template.
    It also retrieves the user's favorite books and passes them to the template.
    """
    user = request.user
    favorite_books = FavoriteBook.objects.filter(user=user)

    my_books = []
    for book in favorite_books:
        book_id = book.book_id
        details = get_book_details(book_id)
        if details:
            my_books.append(details)

    return render(request, "users/user_profile.html", {"user": user, "my_books": my_books})

library/templates/book_detail.html
{% extends "base.html" %} {% block content %}
<div class="mt-4">
  <h1 class="custom-title">{{book.volumeInfo.title}} details</h1>
  <section class="container details-section">
    <div class="text-center">
      {% if book.volumeInfo.imageLinks.thumbnail %}
      <!-- If the book has an image, show it. Otherwise, show a meesage saying that the book has no image. -->
      <img
        src="{{ book.volumeInfo.imageLinks.thumbnail }}"
        height="200"
        width="150"
        class="img-fluid book-cover-img mx-auto d-block"
        alt="Cover of {{ book.volumeInfo.title }}"
        loading="lazy"
      />
      {% else %}
      <p class="text-custom">No cover available</p>
      {% endif %}
    </div>
    <div>
      <!-- This If statement checks if the user is authenticated and if the book is in the user's favorites. If so it shows a message saying that the book is already in the user's favorites. If not, it shows a button to add the book to the user's favorites. If the user is not authenticated, it shows a message saying that the user needs to login to add a book to their favorites. -->
      {% if user.is_authenticated and is_favorite %}
      <p class="fw-bold text-custom">Book is already in your favorites</p>
      {% elif user.is_authenticated %}
      <form action="{% url 'add_book_to_favorites' book.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-favorites mb-4">
          Add to favorites
        </button>
      </form>
      {% else %}
      <p class="text-custom fw-bold">You need to login to add a book to your favorites</p>
      {% endif %}
      {% if book.volumeInfo.authors %}
      <p class="text-custom">
        <b>Author:</b> {{ book.volumeInfo.authors|join:", " }}
      </p>
      {% else %}
      <p class="text-custom">
        <b>Author:</b> Unknown
      </p>
      {% endif %}
      <p class="text-custom">
        <b>Published:</b>
        {% if book.volumeInfo.publishedDate %}
        {{ book.volumeInfo.publishedDate }}
        {% else %}
        Unknown
        {% endif %}
      </p>
      <p class="text-custom">
        <b>Genre:</b>
        {%if book.volumeInfo.categories%}{{book.volumeInfo.categories|join:", " }}
        {%else %}Unknown{% endif %}
      </p>
      {% load tags_filter %}
      <!-- I use the filter_tags filter to remove HTML tags from the description. The truncatewords filter truncates the description to 50 words. -->
      <p class="text-custom">
        <b>Description:</b>
        {% if book.volumeInfo.description %}
        {{book.volumeInfo.description|filter_tags|truncatewords:50 }}
        {% else %}
        No description available
        {% endif %}
      </p>
      <p class="text-custom"><b>Pages:</b>
        {% if book.volumeInfo.pageCount %}
        {{ book.volumeInfo.pageCount }}
        {% else %}
        Unknown
        {% endif %}
      </p>
    </div>
  </section>
</div>
{% endblock %}

library/templates/books_search.html
{% extends "base.html" %}

{% block content %}
<section class="mt-4">
  <h1 class="custom-title">Books List</h1>
  <p class="custom-paragraph">
    Search your favorite books by author, title or genre <br />
    just type in the search bar and click on search
  </p>

  <!-- This is the search bar. It searches by title, author or genre -->
  {% include 'partials/search_bar.html' %}

  <!-- This genre list shows some static genres to search by. It is not dynamic, so it will not change when the user searches. It is just for the user to choose from. If the user selects one, it will take them to the search results page with the selected genre -->
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 genres-container">
    <div class="col custom-col">
      <div class="card custom-card">
        {% load static %}
        <img
          src="{% static 'images/mystery.webp' %}"
          class="card-img-top img-fluid"
          alt="Mystery genre"
        />
        <div class="card-body">
          <h5 class="card-title">Mystery</h5>
          <a
            href="{% url 'books_search_results' %}?genre=Mystery&limit=10&page=1"
            class="btn custom-btn"
            >Search</a
          >
        </div>
      </div>
    </div>
    <div class="col custom-col">
      <div class="card custom-card">
        {% load static %}
        <img
          src="{% static 'images/fiction.webp' %}"
          class="card-img-top img-fluid"
          alt="Fiction genre"
        />
        <div class="card-body">
          <h5 class="card-title">Fiction</h5>
          <a
            href="{% url 'books_search_results' %}?genre=Fiction&limit=10&page=1"
            class="btn custom-btn"
            >Search</a
          >
        </div>
      </div>
    </div>
    <div class="col custom-col">
      <div class="card custom-card">
        {% load static %}
        <img
          src="{% static 'images/fantasy.webp' %}"
          class="card-img-top img-fluid"
          alt="Fantasy genre"
        />
        <div class="card-body">
          <h5 class="card-title">Fantasy</h5>
          <a
            href="{% url 'books_search_results' %}?genre=Fantasy&limit=10&page=1"
            class="btn custom-btn"
            >Search</a
          >
        </div>
      </div>
    </div>
    <div class="col custom-col">
      <div class="card custom-card">
        {% load static %}
        <img
          src="{% static 'images/science.webp' %}"
          class="card-img-top img-fluid"
          alt="Science fiction genre"
        />
        <div class="card-body">
          <h5 class="card-title">Science fiction</h5>
          <a
            href="{% url 'books_search_results' %}?genre=Science+fiction&limit=10&page=1"
            class="btn custom-btn"
            >Search</a
          >
        </div>
      </div>
    </div>
    <div class="col custom-col">
      <div class="card custom-card">
        {% load static %}
        <img
          src="{% static 'images/romance.webp' %}"
          class="card-img-top img-fluid"
          alt="Romance genre"
        />
        <div class="card-body">
          <h5 class="card-title">Romance</h5>
          <a
            href="{% url 'books_search_results' %}?genre=Romance&limit=10&page=1"
            class="btn custom-btn"
            >Search</a
          >
        </div>
      </div>
    </div>
    <div class="col custom-col">
      <div class="card custom-card">
        {% load static %}
        <img
          src="{% static 'images/thriller.webp' %}"
          class="card-img-top img-fluid"
          alt="Thriller genre"
        />
        <div class="card-body">
          <h5 class="card-title">Thriller</h5>
          <a
            href="{% url 'books_search_results' %}?genre=Thriller&limit=10&page=1"
            class="btn custom-btn"
            >Search</a
          >
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

library/templates/partials/search_bar.html
<div class="search-bar">
  <form
    action="{% url 'books_search_results' %}"
    method="get"
    class="d-flex align-items-center gap-2"
  >
    <!-- Search bar for books. It searches by title, author or genre -->
    <label for="search" class="form-label visually-hidden">Search</label>
    <input
      type="text"
      id="search"
      name="search"
      class="form-control custom-input"
      placeholder="Search by title, author or genre"
      aria-label="Search"
      value="{% if request.GET.search %}{{ request.GET.search }}{% elif request.GET.genre %}{{ request.GET.genre }}{% else %}Jesus Christ{% endif %}"
    />

    <!-- Hidden values to control pagination and results limit -->
    <input type="hidden" name="limit" value="10" />
    <input type="hidden" name="page" value="1" />
    <button type="submit" class="btn search-btn m-0">Search</button>
  </form>
</div>

library/templates/results_list.html
<!--
  This template is used to display the results of a search query.
  It shows a list of books with their details and provides pagination.
  The books are displayed in a table format with columns for title, author, genre/category, published date, and book cover.
-->
{% extends "base.html" %} {% block title %} - Results for: {{ title }}{%endblock%}
{% block content %}
<div class="mt-4">
<h1 class="custom-title">Results for: {{ title }}</h1>
{% include 'partials/search_bar.html' %}
{% if books|length > 0%}
<div class="results-list">
  <div class="table-responsive mt-4 mb-4">
    <table class="table table-striped info-table">
      <thead>
        <tr>
          <th scope="col" class="table-text">Title</th>
          <th scope="col" class="table-text">Author</th>
          <th scope="col" class="table-text">Genre/Category</th>
          <th scope="col" class="table-text">Published</th>
          <th scope="col" class="table-text">Book cover</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td class="table-text align-middle max-width-text" title="Go to book {{ book.volumeInfo.title }}">
            <div>
              <p class="fw-bold">{{ book.volumeInfo.title }}</p>
              <a href="{% url 'book_detail' book.id %}" class="custom-link">See book details &#8599;</a>
            </div>
          </td>
          <td class="table-text align-middle max-width-text">
              {% if book.volumeInfo.authors %}
               {{ book.volumeInfo.authors|join:", " }}
              {% else %}
               Unknown
              {% endif %}
          </td>
          <td class="table-text align-middle max-width-text">
            {% if book.volumeInfo.categories %}
               {{ book.volumeInfo.categories|join:", " }}
              {% else %}
               Unknown
              {% endif %}
          </td>
          <td class="table-text align-middle max-width-text">
            {{ book.volumeInfo.publishedDate|default:"Unknown" }}
          </td>
          <td class="table-text">
            <div class="container p-2">
              {% if book.volumeInfo.imageLinks.thumbnail %}

              <img
                src="{{ book.volumeInfo.imageLinks.thumbnail }}"
                height="150"
                width="100"
                class="img-fluid m-auto cover-img"
                alt="Cover of{{ book.title }}"
                loading="lazy"
              />
              {% else %}
              <p>No cover available 😔</p>
              {% endif %}
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <nav>
      <ul class="pagination justify-content-center">
        {% if page > 1 %}
        <li class="page-item">
          <a
            class="page-link"
            href="?search={{query}}&limit={{limit}}&page=1"
            aria-label="First">
            &laquo; First</a>
        </li>
        <li class="page-item">
          <a
            class="page-link"
            href="?search={{query}}&limit={{limit}}&page={{ page|add:"-1" }}"
            aria-label="Previous"
          >
            &lsaquo; Prev</a
          >
        </li>
        {% endif %}

        <li class="page-item active" aria-current="page {{ page }}">
          <span class="page-link">{{page}} of {{total_pages}}</span>
        </li>

        {% if page < total_pages %}
        <li class="page-item">
          <a
            class="page-link"
            href="?search={{query}}&limit={{limit}}&page={{ page|add:"1" }}"
            aria-label="Next">
            Next &rsaquo;</a>
        </li>
        <li class="page-item">
          <a
            class="page-link"
            href="?search={{query}}&limit={{limit}}&page={{ total_pages}}"
            aria-label="Last"
          >
          Last &raquo;</a
          >
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>
{% else %}
<p class="text-custom">No results found</p>
{% endif %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bookme {% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
  </head>
  <body class="body-section container mt-5 mb-5">
    <main class="container-fluid">
      {% include "partials/user_buttons.html" %} {% block content %}
      {%endblock%}
    </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
      crossorigin="anonymous"
    ></script>
  </body>
  <!-- This is the base template for the BookMe project. It includes the necessary Bootstrap and jQuery libraries, as well as the custom CSS and JavaScript files. It also includes the user_buttons.html partial, which is used to display the user buttons on the top right corner of the page. The content block is where the actual content of the page will be displayed. -->
</html>

users/templates/partials/user_buttons.html
<!-- This template is used to display user buttons in the header of the website. -->
<!-- It includes buttons for login, logout, profile, and back to search home. Some If statements are used to check if the user is authenticated and if they are on the search home page. If they are, the profile button is not displayed. If they are not, the profile button is displayed. -->
<div class="d-flex flex-row-reverse gap-3 user-buttons align-items-center">
  {% if user.is_authenticated%}
    <form action="{% url 'users:logout_user' %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-account">Logout</button>
    </form>
    {% if request.path != '/users/profile/' %}
      <a href="{% url 'users:user_profile' %}" class="btn btn-account">Profile</a>
    {% endif %}
    <div class="d-flex flex-column justify-content-center align-items-center">
      <p class="text-custom my-0">Welcome, <b>{{ user.username }}</b></p>
    </div>

  {% else %}
    <a href="{% url 'users:login_user' %}" class="btn btn-account">Login</a>
    <a href="{% url 'users:register_user' %}" class="btn btn-account">Register</a>
  {% endif %}

  {% if request.path != '/' %}
    <a href="/" class="btn btn-home">&larr; Back to search home</a>
  {% endif %}
</div>

users/templates/users/login.html
{% extends "base.html" %}

{% block title %} User Login {% endblock %}

<!-- This template is used to display the login form. It includes a form with a username and password field, a submit button, and a hidden input field for the next page to redirect to after the login. This next page is determined by the 'next' query parameter in the URL. It is used in case the user has made a petition to the website and wants to be redirected to the petition page after logging in. -->
{% block content %}
    <h1 class="custom-title">User Login</h1>
    <div class="form-container">
        <form action="{% url 'users:login_user' %}" method="post" class="custom-form">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <button type="submit" class="btn form-btn">Login</button>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}

{% block title %} Register user {% endblock %}

<!-- This template is used to display the registration form. It includes a form with a username, email, password, and confirm password fields, a submit button. -->
{% block content %}
<h1 class="custom-title">Register user</h1>
<div class="form-container">
  <form action="{% url 'users:register_user' %}" method="post" class="custom-form">
    {% csrf_token %} {{ form }}
    <button type="submit" class="btn form-btn">Register</button>
  </form>
</div>
{% endblock %}

users/templates/users/user_profile.html
{% extends "base.html" %}

{% block title %} Welcome, {{ user.username }} {% endblock %}

<!-- This template is used to display the user's profile page. It includes a section with a title and a list of the user's favorite books. If the user has no favorite books, it shows a message saying that they don't have any favorite books yet. -->
{% block content %}
<section class="mt-4">
    <h1 class="custom-title">Your favorite books</h1>
    {% if my_books %}
    <div class="favorite-books">
        {% for book in my_books %}
        <div class="favorite-book">
            {% if book.volumeInfo.title %}
            <h2>{{book.volumeInfo.title|truncatewords:10}}</h2>
            {% else %}
            <h2>Unknown title</h2>
            {% endif %}
            {% if book.volumeInfo.authors %}
            <p><b>Author(s):</b> {{book.volumeInfo.authors|join:", " }}</p>
            {% else %}
            <p><b>Author(s):</b> Unknown</p>
            {% endif %}
            {% if book.volumeInfo.imageLinks.thumbnail %}
            <img src="{{book.volumeInfo.imageLinks.thumbnail}}" alt="Book cover {{book.volumeInfo.title}}" class="img-fluid" width="150" height="200">
            {% else %}
            <p>No cover available</p>
            {% endif %}
            <a href="{% url 'book_detail' book.id %}" class="btn btn-favorites">See book details &#8599;</a>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>You don't have any favorite books yet</p>
    {% endif %}
</section>
{% endblock content %}